[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "npm ci && npm run build"
]

[phases.deploy]
cmds = ["php artisan migrate --force"]

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "18"